### PR TITLE
WIP: Add necessary endpoints for demo support.

### PR DESCRIPTION
**Pull request by subdavis**
Effectively stolen from inpainting.

Don't merge yet.

### CODE REVIEW

**Comment by subdavis** [comment]
@zachmullen Could we talk about running an rshiny server managed by girder?

I _think_ the idea is to have the RShiny server run as a girder-worker task, but I'm not totally sure about how the life-cycle should work.  What are the conditions for stopping the server, and how will we achieve that?  Celery revoke?

Is there any prior art for managing resource servers under girder worker that I could brush up on?  

Thanks!

**Comment by zachmullen** [comment]
I was thinking the RShiny server would be separate from Girder, and Girder could simply point to it with a directory path.

**Comment by subdavis** [comment]
Ok.  How were you thinking of managing those servers?  From what I understand, we'll need a separate instance of the server for each directory, and I'm not sure how to know when the server can be torn down.

I don't know a ton about R/RShiny so I may be over-complicating here.

**Comment by zachmullen** [comment]
>  From what I understand, we'll need a separate instance of the server for each directory

Is that because there is only one R kernel per server, or because a session cannot be parametrized by directory? Sorry, I don't know much about RShiny

**Comment by subdavis** [comment]
I'm going by what I've read of the visualization script.  It looks to me like 1 kernel per server.

https://github.com/KitwareMedical/UTM/blob/master/Scripts/Shiny/display.shiny.R#L60

I also read http://www.science.smith.edu/dftwiki/index.php/Tutorial:_Shiny_Application_to_Visualize_Data_Generated_On-the-Fly#Python_CGI_script

In that example a separate python CGI application generates data into the working directory of the shiny app.

**Comment by zachmullen** [comment]
That sounds like the right approach. We may need @samuelgerber to help us with the R server parts.

**Comment by suppechasper** [comment]
Does this answer your question:
http://docs.rstudio.com/shiny-server/#host-a-directory-of-applications
?

**Comment by subdavis** [comment]
@suppechasper I don't _think_ so.  A directory of applications is still a finite set right?  Our goal is to parameterize to allow any arbitrary girder directory to be the working directory for this app.

**Comment by zachmullen** [comment]
Right, what we need to do is take a URL parameter that names a specific directory and then pass that into the underlying R script at startup time of the session. We can look into the R script itself to try and figure out the best way to do that, it will just involve us learning a bit about R/RShiny

**Comment by suppechasper** [comment]
Within the R script in shiny you can do this with:

https://shiny.rstudio.com/reference/shiny/0.14/parseQueryString.html

In particular with (I think) :
parseQueryString(session$clientData$url_search)

https://shiny.rstudio.com/articles/client-data.html

**Pull request closed without merging**
